name: Sync With Hugging Face Hub
description: An action to sync files on GitHub with a repo on the Hugging Face Hub (https://hf.co)
author: nateraw
branding:
  icon: upload-cloud
  color: yellow

inputs:
  # subdirectory:
  #   type: string
  #   default: ''
  huggingface_repo_id:
    required: true
    type: string
  hf_token:
    required: true
  repo_type:
    type: string
    default: 'space'
  # space_sdk:
  #   type: string
  #   default: 'gradio'
  private:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout Source GitHub Repo to Push
      uses: actions/checkout@v2

    - name: Install Hugging Face Hub CLI tool
      shell: bash
      run: |
        pip install huggingface-hub  # hf-transfer

    - name: Push to Hugging Face Hub
      shell: bash
      # env:
      #   HF_HUB_ENABLE_HF_TRANSFER: 1
      run: |
        huggingface-cli upload \
          ${{ inputs.huggingface_repo_id }} . . \
          --repo-type ${{ inputs.repo_type }}  \
          --token ${{ inputs.hf_token }} \
          --quiet
