name: Sync With Hugging Face Hub
description: An action to sync files on GitHub with a repo on the Hugging Face Hub (https://hf.co)
author: nateraw
branding:
  icon: upload-cloud
  color: yellow

inputs:
  subdirectory:
    type: string
    default: ''
  huggingface_repo_id:
    required: true
    type: string
  hf_token:
    required: true
  repo_type:
    type: string
    default: 'space'
  space_sdk:
    type: string
    default: 'gradio'
  private:
    type: boolean
    default: false
  branch:
    type: string
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Checkout Action GitHub Repo
      uses: actions/checkout@v2
      with:
        repository: 'juhoinkinen/huggingface-sync-action'

    - name: Checkout Source GitHub Repo to Push
      uses: actions/checkout@v2
      with:
        ref: "${{ inputs.branch }}"
        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: cloned_github_repo

    - name: Push to hub
      shell: bash
      run: |
        cd cloned_hf_action_repo
        ls -l  # debug
        pip install -r requirements.txt
        cd ..
        ls -l cloned_hf_action_repo  # debug
        python cloned_hf_action_repo/sync_with_spaces.py \
          --repo_id ${{ inputs.huggingface_repo_id }} \
          --directory "cloned_github_repo/${{ inputs.subdirectory }}" \
          --token ${{ inputs.hf_token }} \
          --repo_type ${{ inputs.repo_type }} \
          --space_sdk ${{ inputs.space_sdk }} \
          --private ${{ inputs.private }}
